export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const RECEIVE_POST = 'RECEIVE_POST';
export const RESET_POSTS = 'RESET_POSTS';

export const RECEIVE_SCHEDULED_POSTS = 'RECEIVE_SCHEDULED_POSTS';
export const RECEIVE_SCHEDULED_POST = 'RECEIVE_SCHEDULED_POST';
export const RESET_SCHEDULED_POSTS = 'RESET_SCHEDULED_POSTS';
export const RECEIVE_REMOVE_SCHEDULED_POST = 'RECEIVE_REMOVE_SCHEDULED_POST';

export const RECEIVE_ACCOUNTS = 'RECEIVE_ACCOUNTS';
export const RECEIVE_REMOVE_ACCOUNT = 'RECEIVE_REMOVE_ACCOUNT';

export const RECEIVE_RSS_FEEDS = 'RECEIVE_RSS_FEEDS';
export const RECEIVE_RSS_FEED = 'RECEIVE_RSS_FEED';
export const RECEIVE_REMOVE_RSS_FEED = 'RECEIVE_REMOVE_RSS_FEED';

export const RECEIVE_USER = 'RECEIVE_USER';
