export const RECEIVE_FACEBOOK_POSTS = 'RECEIVE_FACEBOOK_POSTS';
export const RECEIVE_TWITTER_POSTS = 'RECEIVE_TWITTER_POSTS';
export const RECEIVE_LINKEDIN_POSTS = 'RECEIVE_LINKEDIN_POSTS';
export const RECEIVE_RSS_POSTS = 'RECEIVE_RSS_POSTS';

export const RECEIVE_FACEBOOK_POST = 'RECEIVE_FACEBOOK_POST';
export const RECEIVE_TWITTER_POST = 'RECEIVE_TWITTER_POST';
export const RECEIVE_LINKEDIN_POST = 'RECEIVE_LINKEDIN_POST';
export const RECEIVE_RSS_POST = 'RECEIVE_RSS_POST';

export const RESET_FACEBOOK_POSTS = 'RESET_FACEBOOK_POSTS';
export const RESET_TWITTER_POSTS = 'RESET_TWITTER_POSTS';
export const RESET_LINKEDIN_POSTS = 'RESET_LINKEDIN_POSTS';
export const RESET_RSS_POSTS = 'RESET_RSS_POSTS';

export const RECEIVE_FACEBOOK_SCHEDULED_POSTS = 'RECEIVE_FACEBOOK_SCHEDULED_POSTS';
export const RECEIVE_TWITTER_SCHEDULED_POSTS = 'RECEIVE_TWITTER_SCHEDULED_POSTS';
export const RECEIVE_LINKEDIN_SCHEDULED_POSTS = 'RECEIVE_LINKEDIN_SCHEDULED_POSTS';
export const RECEIVE_RSS_SCHEDULED_POSTS = 'RECEIVE_RSS_SCHEDULED_POSTS';

export const RECEIVE_FACEBOOK_SCHEDULED_POST = 'RECEIVE_FACEBOOK_SCHEDULED_POST';
export const RECEIVE_TWITTER_SCHEDULED_POST = 'RECEIVE_TWITTER_SCHEDULED_POST';
export const RECEIVE_LINKEDIN_SCHEDULED_POST = 'RECEIVE_LINKEDIN_SCHEDULED_POST';
export const RECEIVE_RSS_SCHEDULED_POST = 'RECEIVE_RSS_SCHEDULED_POST';

export const RECEIVE_REMOVE_FACEBOOK_SCHEDULED_POST = 'RECEIVE_REMOVE_FACEBOOK_SCHEDULED_POST';
export const RECEIVE_REMOVE_TWITTER_SCHEDULED_POST = 'RECEIVE_REMOVE_TWITTER_SCHEDULED_POST';
export const RECEIVE_REMOVE_LINKEDIN_SCHEDULED_POST = 'RECEIVE_REMOVE_LINKEDIN_SCHEDULED_POST';
export const RECEIVE_REMOVE_RSS_SCHEDULED_POST = 'RECEIVE_REMOVE_RSS_SCHEDULED_POST';

export const RESET_FACEBOOK_SCHEDULED_POSTS = 'RESET_FACEBOOK_SCHEDULED_POSTS';
export const RESET_TWITTER_SCHEDULED_POSTS = 'RESET_TWITTER_SCHEDULED_POSTS';
export const RESET_LINKEDIN_SCHEDULED_POSTS = 'RESET_LINKEDIN_SCHEDULED_POSTS';

export const RECEIVE_ACCOUNTS = 'RECEIVE_ACCOUNTS';
export const RECEIVE_REMOVE_ACCOUNT = 'RECEIVE_REMOVE_ACCOUNT';

export const RECEIVE_RSS_FEEDS = 'RECEIVE_RSS_FEEDS';
export const RECEIVE_RSS_FEED = 'RECEIVE_RSS_FEED';
export const RECEIVE_REMOVE_RSS_FEED = 'RECEIVE_REMOVE_RSS_FEED';

export const RECEIVE_USER = 'RECEIVE_USER';
