export const RECEIVE_FACEBOOK_POSTS = 'RECEIVE_FACEBOOK_POSTS';
export const RECEIVE_TWITTER_POSTS = 'RECEIVE_TWITTER_POSTS';
export const RECEIVE_LINKEDIN_POSTS = 'RECEIVE_LINKEDIN_POSTS';
export const RECEIVE_RSS_POSTS = 'RECEIVE_RSS_POSTS';

export const RECEIVE_FACEBOOK_SCHEDULED_POSTS = 'RECEIVE_FACEBOOK_SCHEDULED_POSTS';
export const RECEIVE_TWITTER_SCHEDULED_POSTS = 'RECEIVE_TWITTER_SCHEDULED_POSTS';
export const RECEIVE_LINKEDIN_SCHEDULED_POSTS = 'RECEIVE_LINKEDIN_SCHEDULED_POSTS';
export const RECEIVE_RSS_SCHEDULED_POSTS = 'RECEIVE_RSS_SCHEDULED_POSTS';

export const RECEIVE_ACCOUNTS = 'RECEIVE_ACCOUNTS';
export const RECEIVE_REMOVE_ACCOUNT = 'RECEIVE_REMOVE_ACCOUNT';
export const RECEIVE_RSS_FEEDS = 'RECEIVE_RSS_FEEDS';
export const RECEIVE_RSS_FEED = 'RECEIVE_RSS_FEED';
export const RECEIVE_REMOVE_RSS_FEED = 'RECEIVE_REMOVE_RSS_FEED';

export const RECEIVE_USER = 'RECEIVE_USER';
